# Generated by Django 4.2.7 on 2026-02-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the offer', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Main image for the offer', null=True, upload_to='offers/')),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Business user who created this offer', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Package name', max_length=100)),
                ('revisions', models.IntegerField(default=0, help_text='Number of revisions included')),
                ('delivery_time_in_days', models.IntegerField(help_text='Delivery time in days')),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price', max_digits=10)),
                ('features', models.JSONField(default=list, help_text='List of features included')),
                ('offer_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], help_text='Package tier type', max_length=20)),
                ('offer', models.ForeignKey(help_text='Parent offer', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers.offer')),
            ],
            options={
                'verbose_name': 'Offer Detail',
                'verbose_name_plural': 'Offer Details',
                'ordering': ['offer', 'offer_type'],
                'unique_together': {('offer', 'offer_type')},
            },
        ),
    ]
